version: 1.2
workflows:
  - name: ONT_Autocycler
    subclass: wdl
    primaryDescriptorPath: /wdls/workflows/ONT_Autocycler.wdl
    latestTagAsDefault: 'true'
    authors:
      - orcid: "0000-0002-6006-0641"
  - name: Dnaapler
    subclass: wdl
    primaryDescriptorPath: /wdls/tasks/Dnaapler.wdl
    authors:
      - orcid: "0000-0002-6006-0641"
  - name: BandageNG
    subclass: wdl
    primaryDescriptorPath: /wdls/workflows/BandageNG.wdl
    authors:
      - orcid: "0000-0002-6006-0641"
  - name: ONT_AutocyclerClean
    subclass: wdl
    primaryDescriptorPath: /wdls/workflows/ONT_AutocyclerClean.wdl
    latestTagAsDefault: 'true'
    authors:
      - orcid: "0000-0002-6006-0641"
